# Generated by Django 3.1 on 2020-08-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0003_auto_20200811_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
